# APPLICATION CONFIGURATION
server.port=8080
server.servlet.context-path=/api
spring.application.name=auth

# JWT KEYS
jwt.public.key=classpath:public_key.pem
jwt.private.key=classpath:private_key.pem

# ADMIN USER CREDENTIALS
admin.email=admin@gmail.com
admin.password=admin

# JavaMailSender CONFIGURATION
spring.mail.host=<host>
spring.mail.port=<port>
spring.mail.username=<username>
spring.mail.password=<password>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# DATABASE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update

