# APPLICATION CONFIGURATION
server.port=9090
spring.application.name=auth
app.base_url=http://localhost:9090

# JWT KEYS
jwt.public.key=classpath:public_key.pem
jwt.private.key=classpath:private_key.pem

# ADMIN USER CREDENTIALS
admin.email=admin@gmail.com
admin.password=password

# JavaMailSender CONFIGURATION
spring.mail.host={EMAIL_HOST}
spring.mail.port={EMAIL_PORT}
spring.mail.username={EMAIL_USERNAME}
spring.mail.password={EMAIL_PW}
spring.mail.properties.mail.smtp.auth=true

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:h2:mem:authDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# PROFILE CONFIGURATION
logging.level.root=DEBUG
logging.level.org.springframework=DEBUG