# APPLICATION CONFIGURATION
server.port=${SERVER_PORT}
spring.application.name=auth
app.base_url=${BASE_URL}

# JWT KEYS
jwt.public.key=${PUBLIC_KEY}
jwt.private.key=${PRIVATE_KEY}

# ADMIN USER CREDENTIALS
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PW}

# JavaMailSender CONFIGURATION
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PW}
spring.mail.properties.mail.smtp.auth=true

# DATABASE CONFIGURATION
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.url=${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=${DATABASE_DDL}

# PROFILE CONFIGURATION
logging.level.root=WARN
logging.level.org.springframework.web=ERROR
